
export const TIPO_PERFORACION__ABIERTO = [ "OS","ON","V","T","B"];
export const TIPO_PERFORACION__CORAZONADOS = [ "CS","CN","C"];

export const TIPOPOZO_DESCRIPCION_NUCLEOS = 'TIPOPOZO_DESCRIPCION_NUCLEOS';
export const TIPOPOZO_DATOS_CARBON = 'TIPOPOZO_DATOS_CARBON';
